<?php

function deposit_theme($existing, $type, $theme, $path) {
	return array(
		'deposit_page_template' => array(
			'template' => 'templates/deposits-list'
		),
		'deposit_calculate_template' => array(
			'template' => 'templates/deposit_calculate_template',
		),
		'deposit_calculate_result_template' => array(
			'template' => 'templates/deposit_calculate_result_template',
		)
	);
}

function deposit_menu() {
	return array(
		'deposits' => array(
			'title' => t('Deposit calculator'),
			'page callback' => 'deposit_list',
			'access callback' => TRUE
		),
		'deposits/calculate/%' => array(
			'title' => t('Deposit calculator'),
			'page callback' => 'deposit_calculate',
			'access callback' => TRUE
		),
		'deposits/calculate/result' => array(
			'title' => t('Deposit calculator'),
			'page callback' => 'deposit_calculate_result',
			'access callback' => TRUE
		),
	);
}

function deposit_list(){
	$lang = $GLOBALS['language']->language;
	$content_type = 'deposits';
	$deposits = node_load_multiple(array(), array('type' => $content_type, 'status' => 1, 'language' => $lang));

	return theme('deposit_page_template', array('deposits' => $deposits));
}

function deposit_calculate(){
	$nid = arg(2);
	$node = node_load($nid);
	return theme('deposit_calculate_template', array('deposit' => $node));
}
function deposit_calculate_result(){
	if(($total_sum = $_REQUEST['total_sum']) && ($deposit_nid = $_REQUEST['deposit_num'])){
			$deposit = node_load($deposit_nid);
	}else{
		$redirect_url = ($_SERVER['HTTP_REFERER'])? $_SERVER['HTTP_REFERER'] : '/deposits/calculate';
		header("Location: {$redirect_url}");
		exit();
	}
	$percent = (int)$deposit->field_deposit_percent['und'][0]['value'];
	$total_sum_for_full_period = ($total_sum / 100) * $percent;

	$sum_for_per_month = $total_sum_for_full_period / $deposit->field_deposit_limit['und'][0]['value'];
	$currency_type = ($deposit->field_currency_type['und'][0]['value'] == 'foreign_currency')? '$' : t('som');
	$context = array(
		'total_sum_for_full_period' => $total_sum_for_full_period,
		'sum_for_per_month' => $sum_for_per_month,
		'currency_type' => $currency_type
	); 
	return theme('deposit_calculate_result_template', $context);
}